{
 "title": "Pi Pool",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "adopted_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_Forge_adopted_int"
    }
   ]
  },
  {
   "title": "forged_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_Forge_forged_int"
    }
   ]
  },
  {
   "title": "not_forge_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_Forge_could_not_forge_int"
    }
   ]
  },
  {
   "title": "txsProcessedNum_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_txsProcessedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "slotInEpoch_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "slotNum_int",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_slotNum_int"
    }
   ]
  },
  {
   "title": "C1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(Prometheus_cpu_seconds_total{mode=\"idle\",alias=\"N1\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (Prometheus_memory_MemAvailable_bytes{alias=\"N1\"} / (Prometheus_memory_MemTotal_bytes{alias=\"N1\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((Prometheus_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"N1\"} * 100) / Prometheus_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"N1\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (Prometheus_memory_SwapFree_bytes{alias=\"N1\"} / Prometheus_memory_SwapTotal_bytes{alias=\"N1\"})) * 100",
     "legendFormat": "Zram"
    }
   ]
  },
  {
   "title": "epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_epoch_int"
    }
   ]
  },
  {
   "title": "KES rotation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_Prometheus_metrics_remainingKESPeriods_int * 1.45)",
     "legendFormat": "Days left"
    }
   ]
  },
  {
   "title": "connectedPeers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "connectedPeers_int",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "connectedPeers" }
   ],
   "targets": [
    {
     "color": "semi-dark-purple",
     "expr": "cardano_Prometheus_metrics_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - Prometheus_boot_time_seconds{alias=\"N1\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_slotInEpoch_int/432000",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU 1 minute average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(Prometheus_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "txsInMempool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_txsInMempool_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Prometheus_timex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "Prometheus_timex_maxerror_seconds * 1000000",
     "legendFormat": "{{alias}} max error"
    },
    {
     "expr": "Prometheus_timex_estimated_error_seconds * 1000000",
     "legendFormat": "{{alias}} est error"
    }
   ]
  },
  {
   "title": "mempoolBytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_mempoolBytes_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "slotsMissedNum_int",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_slotsMissedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "chainDensity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cardano_Prometheus_metrics_density_real * 2000 ",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Prometheus_memory_MemFree_bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Prometheus_thermal_zone_temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "Prometheus_thermal_zone_temp*1.8+32",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(Prometheus_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    },
    {
     "expr": "irate(Prometheus_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(Prometheus_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(Prometheus_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}